# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python run.py -m hparams_search=conv3d_optuna experiment=example_simple

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
optimized_metric: "MSE/Validation_epoch"

hydra:
  # here we define Optuna hyperparameter search
  # it optimizes for value returned from function with @hydra.main decorator
  # learn more here: https://hydra.cc/docs/next/plugins/optuna_sweeper
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # number of experiments that will be executed
    n_trials: 20

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    search_space:
      model.conv3d_channels:
        type: categorical
        choices: [16, 32, 64]
      model.fc1_output_features:
        type: categorical
        choices: [16, 32, 64, 128]
      model.fc2_output_features:
        type: categorical
        choices: [ 16, 32, 64, 128 ]
      model.fc3_output_features:
        type: categorical
        choices: [ 16, 32, 64, 128 ]

