_target_: predict_pv_yield.models.conv3d.model_sat_nwp.Model

include_pv_yield: True
include_nwp: False
forecast_minutes: 120
history_minutes: 30
number_of_conv3d_layers: 6
image_size_pixels: 24
number_sat_channels: 11
conv3d_channels: 32
fc1_output_features: 128
fc2_output_features: 128
fc3_output_features: 64
output_variable: gsp_yield
