_target_: predict_pv_yield.models.perceiver.perceiver_conv3d_nwp_sat.Model

forecast_minutes: 30
history_minutes: 60
batch_size: 32
num_latents: 24
latent_dim: 24
embedding_dem: 0
output_variable: gsp_yield
conv3d_channels: 8
use_future_satellite_images: 0
